insert into Store values (1,'Sahar Road, Andheri(e)Hyderabad, Telangana','Pizza Hut','4.0', 'open');
insert into Store values (2,'Alwal Secunderabad, Telangana','Bawarchi','4.3', 'open');
insert into Store values (3,'J M Chamber,N Street, Chinch Bunder, Telangana','KFC','2.0', 'close');
insert into Store values (4,'G.B.S Enclave, Thirumalgherry, Telangana','Grill 9','4.2', 'open');
insert into Store values (5,'Supariwala Bldg, Opp Kem Hospital Main Gate, Mumbai','Mozarella pizza','3.9', 'open');
insert into Store values (6,'Hyderabad, Telangana','5th Avenue','4.9', 'close');

insert into Item values (1, '50g of pure banana fry', 'Banana chips', '100', 1);
insert into Item values (2, 'panner filled pizza', 'Paneer pizza', '175', 1);
insert into Item values (4, 'Made of pure Paneer', 'Paneer tikka', '239', 1);
insert into Item values (5, 'Veggie! ', 'Veg Pizza', '160', 1);
insert into Item values (3, 'Non-Veg Mutton', 'Mutton Biryani', '150', 2);
insert into Item values (6, 'Spiced Chicken', 'Orange Chicken', '130', 2);
insert into Item values (7, 'Thamed Fried Chicken', 'Fried Chicken', '245', 2);
insert into Item values (8, 'Chinese style chicken', 'Dragon Chicken', '199', 2);
insert into Item values (9, 'gralic spiced', 'Chips', '45', 5);
insert into Item values (10, 'Non-Veg', 'Burger', '250', 1);
insert into Item values (11, 'gralic spiced', 'Chips', '55', 1);
insert into Item values (12, 'panner filled pizza', 'Paneer pizza', '175', 5);
insert into Item values (13, 'Made of pure Paneer', 'Paneer tikka', '239', 5);
insert into Item values (14, 'Veggie! ', 'Veg Pizza', '160', 5);
insert into Item values (18, 'Honey grazed', 'Pancake', '130', 5);
insert into Item values (17, 'Hot!! and spicy!', 'Samosa', '245', 5);
insert into Item values (15, 'Spiced Chicken', 'Orange Chicken', '130', 5);
insert into Item values (16, 'Thamed Fried Chicken', 'Fried Chicken', '245', 5);
insert into Item values (19, 'Hot!! and spicy!', 'Samosa', '245', 2);
insert into Item values (20, 'Tasty!', 'Gulab Jamun', '189', 1);
insert into Item values (21, 'Tasty!', 'Gulab Jamun', '189', 2);
insert into Item values (22, 'Tasty!', 'Gulab Jamun', '189', 4);
insert into Item values (23, 'Tasty!', 'Gulab Jamun', '189', 5);
insert into Item values (24, 'Sweet!', 'Donuts', '199', 5);
insert into Item values (25, 'Tasty!', 'Jilebi', '109', 1);
insert into Item values (26, '5 pieces', 'Blueberry Muffins', '200', 5);
insert into Item values (27, '8 pieces', 'Lollipop', '200', 4);
insert into Item values (28,'Awesome!', 'French Fry Burger','150',4);
insert into Item values (29, 'Spiced Chicken', 'Orange Chicken', '130', 4);
insert into Item values (30, 'Thamed Fried Chicken', 'Fried Chicken', '245', 4);
insert into Item values (31, 'Chinese style chicken', 'Dragon Chicken', '199', 4);
insert into Item values (32, 'gralic spiced', 'Chips', '45', 4);
insert into Item values (33, 'Honey grazed', 'Pancake', '130', 4);

insert into Customer values(1,'admin', 'admin');